--------------------------------------------------------
--  SH1 MTR - Create Materialised Views
--------------------------------------------------------

CREATE MATERIALIZED VIEW "TUQRPCEL001"."MV_FB1_T_TRADES_LDD"
BUILD IMMEDIATE 
REFRESH FAST 
--START WITH sysdate+0 NEXT SYSDATE + 1/60/60/24
WITH ROWID 
USING DEFAULT LOCAL ROLLBACK SEGMENT
USING ENFORCED CONSTRAINTS 
DISABLE QUERY REWRITE
AS SELECT * FROM "FB1_T_TRADES_LDD"@"DBL_HVCELO.WORLD" "FB1_T_TRADES_LDD";

GRANT SELECT ON  "TUQRPCEL001"."MV_FB1_T_TRADES_LDD" TO R_CDS_RO_ALL;